config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user/registrations' }
  resources :users, only: [:show]
  resources :user_stocks, except: [:edit, :update, :show]
  resources :friendships

  root to: 'welcome#index'

  get 'my_portfolio',   to: 'users#my_portfolio'
  get 'search_stocks',  to: 'stocks#search'
  get 'my_friends',     to: 'users#my_friends'
  get 'search_friends', to: 'users#search'
  post 'add_friend',    to: 'users#add_friend'
end

app/models/friendship.rb
# Model for Friendship between Users
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
# Model for stock, with several class functions
class Stock < ActiveRecord::Base
  has_many :user_stocks
  has_many :users, through: :user_stocks

  class << self
    def new_from_lookup(ticker)
      looked_up = StockTicker.new(ticker)

      name = looked_up.name

      return nil unless name

      new_stock = new(ticker: looked_up.symbol, name: name)
      new_stock.last_price = new_stock.price
      new_stock
    end

    def find_by_ticker(ticker)
      where(ticker: ticker).first
    end
  end

  def price
    StockTicker.new(ticker).price
  end
end

# Shim for stock_quote gem
class StockTicker
  attr_reader :symbol

  def initialize(symbol)
    @symbol = symbol
    @ticker = StockQuote::Stock.quote(symbol)
  end

  def price
    return "#{closing} (Closing)" if closing
    return "#{opening} (Opening)" if opening

    'Unavailable'
  end

  def name
    @ticker.name
  end

  private

  def closing
    @ticker.close
  end

  def opening
    @ticker.open
  end
end

app/models/user.rb
# Model for User
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :recoverable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  class << self
    def search(param)
      return user.none if param.blank?

      param.strip!
      param.downcase!

      (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    end

    def first_name_matches(param)
      matches('first_name', param)
    end

    def last_name_matches(param)
      matches('last_name', param)
    end

    def email_matches(param)
      matches('email', param)
    end

    def matches(field_name, param)
      where("LOWER(#{field_name}) LIKE ?", "%#{param}%")
    end
  end

  def full_name
    "#{first_name} #{last_name}".strip
  end

  def can_add_stock?(ticker)
    under_stock_limit? &&
      !stock_already_added?(ticker)
  end

  def under_stock_limit?
    user_stocks.count < 10
  end

  def stock_already_added?(ticker)
    stock = Stock.find_by_ticker ticker
    return false unless stock

    user_stocks.where(stock_id: stock.id).exists?
  end

  def not_friends_with?(other)
    friendships.where(friend_id: other.id).count < 1
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end
end

app/models/user_stock.rb
# Model for Tracked stock for User
class UserStock < ActiveRecord::Base
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
# Base application comtroller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user! # Require logged-in user for everything
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    friend = current_user.friendships.where(friend_id: params[:id]).first
    friend.destroy
    respond_to do |format|
      format.html { redirect_to my_friends_path, notice: 'The friend was removed successfully' }
    end
  end
end

app/controllers/stocks_controller.rb
# Controller for stock searching
class StocksController < ApplicationController
  def search
    if params[:stock]
      @stock =   Stock.find_by_ticker params[:stock]
      @stock ||= Stock.new_from_lookup params[:stock]
    end

    if @stock
      render partial: 'lookup'
    else
      render status: :not_found, nothing: true
    end
  end
end

app/controllers/user/registrations_controller.rb
# Controller for user registration to allow for first and last names
class User::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name)
    devise_parameter_sanitizer.for(:account_update).push(:first_name, :last_name)
  end
end

app/controllers/user_stocks_controller.rb
# Controller fur user tracked stocks
class UserStocksController < ApplicationController
  # GET /user_stocks
  # GET /user_stocks.json
  def index
    @user_stocks = UserStock.all
  end

  # GET /user_stocks/new
  def new
    @user_stock = UserStock.new
  end

  # POST /user_stocks
  # POST /user_stocks.json
  def create
    @user_stock = create_record

    respond_to do |format|
      if @user_stock.save
        ticker = @user_stock.stock.ticker

        format.html do
          redirect_to my_portfolio_path,
                      notice: "The stock #{ticker} was successfully added."
        end
        format.json { render :show, status: :created, location: @user_stock }
      else
        format.html { render :new }
        format.json do
          render json: @user_stock.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /user_stocks/1
  # DELETE /user_stocks/1.json
  def destroy
    @user_stock = UserStock.find(params[:id])
    @user_stock.destroy

    respond_to do |format|
      format.html do
        redirect_to my_portfolio_path,
                    notice: 'The stock was successfully removed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the internet, only allow the white list through.
  def user_stock_params
    params.require(:user_stock).permit(:user_id, :stock_id)
  end

  def create_record
    if params[:stock_id].present?
      UserStock.new stock_id: params[:stock_id], user: current_user
    else
      create_from_stock_record
    end
  end

  def create_from_stock_record
    stock = Stock.find_by_ticker stock_ticker
    return record_from_stock(stock) if stock

    stock = Stock.new_from_lookup stock_ticker
    return record_from_stock(stock) if stock.save

    flash[:error] = 'The stock is not currently available.'
    nil
  end

  def record_from_stock(stock)
    UserStock.new stock: stock, user: current_user
  end

  def stock_ticker
    params[:stock_ticker]
  end
end

app/controllers/users_controller.rb
# Controller fur users
class UsersController < ApplicationController
  def show
    @user        = User.find params[:id]
    @user_stocks = @user.stocks
  end

  def my_portfolio
    @user        = current_user
    @user_stocks = @user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def search
    @users = User.search params[:search_param]

    if @users
      @users = current_user.except_current_user @users
      render partial: 'friends/lookup'
    else
      render status: :not_found, nothing: true
    end
  end

  def add_friend
    @friend = User.find params[:friend]

    current_user.friendships.build friend: @friend
    if current_user.save
      redirect_to my_friends_path, notice: 'That friend has been added.'
    else
      redirect_to my_friends_path,
                  flash[:error] = 'There was an error with adding that friend.'
    end
  end
end

app/controllers/welcome_controller.rb
# Controller for home page
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# General helpers for views
module ApplicationHelper
end

app/views/common/_spinner.html.erb
<div id="spinner" class="row text-center">
  <i class="fa fa-spinner fa-spin fa-2x"></i> Processing...
</div>

app/views/friends/_lookup.html.erb
<div id="friend-lookup">
  <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
    <div class="form-group row no-padding text-center">
      <div class="col-sm-4">
        <%= text_field_tag :search_param, params[:search_param],
            placeholder: 'name or email', autofocus: true,
            class: 'form-control search-box imput-lg' %>
      </div>
      <div class="col-sm-2">
        <%= button_tag type: :submit, class: 'btn btn-success' do %>
          <i class="fa fa-search"></i> Find Friend
        <% end %>
      </div>
    </div>
  <% end %>

  <%= render 'common/spinner' %>

  <% if @users %>
    <% if @users.any? %>
      <div id="friend-lookup-results" class="well results-block">
        <table class="table search-results-table">
          <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><strong>Name:</strong> <%= user.full_name %></td>
              <td><strong>Email:</strong> <%= user.email %></td>
              <td>
                <strong>Profile:</strong>
                <%= link_to 'Show profile', user, class: 'btn btn-xs btn-success' %>
                <% if current_user.not_friends_with? user %>
                  <%= link_to 'Add as friend', add_friend_path(user: current_user, friend: user),
                              method: :post, class: 'btn btn-xs btn-success' %>

                <% else %>
                  <span class="label label-primary">You are friends.</span>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <p class="lead">No-one matches the search criteria.</p>
    <% end %>
  <% end %>

  <div id="friend-lookup-errors"></div>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <a class="navbar-brand" href="/">Finance Tracker</a>
    <% if current_user %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav col-md-6">
          <li><%= link_to "My portfolio", my_portfolio_path %></li>
          <li><%= link_to "My profile", edit_registration_path(current_user) %></li>
          <li><%= link_to "My friends", my_friends_path %></li>
        </ul>
        <ul class="nav navbar-right col-md-4">
          <li class="col-md-8 user-name text-right">
            <i classs="fa fa-user"></i>
            <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
          </li>
          <li class="col-md-4 logout">
            <%= link_to 'Log out', destroy_user_session_path,
                        class: 'btn btn-xs btn-danger', method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Complete Finance Tracker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>

      <footer>
        <p>This Application is created by Tasnim Mansur in Lanetteam</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-sm-10">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Symbol</th>
          <th>Current Price</th>
          <% if @user.id == current_user.id %>
            <th>Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @user_stocks.each do |stock| %>
          <tr>
            <td><%= stock.name %></td>
            <td><%= stock.ticker %></td>
            <td><%= stock.price %></td>
            <% if @user.id == current_user.id %>
              <td>
                <%= link_to 'Remove', user_stock_path(stock), method: :delete,
                           data:{ confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/stocks/_lookup.html.erb
<div id="stock-lookup">
  <%= form_tag search_stocks_path, remote: true, method: :get, id: 'stock-lookup-form' do %>
    <div class="form-group row no-padding text-center">
      <div class="col-sm-4">
        <%= text_field_tag :stock, params[:stock], placeholder: 'Stock ticker symbol', autofocus: true,
            class: 'form-control search-box input-lg' %>
      </div>
      <div class="col-sm-2">
        <%= button_tag type: :submit, class: 'btn btn-success' do %>
          <i class="fa fa-search"></i> Look up a stock
        <% end %>
      </div>
    </div>
  <% end %>

  <%= render 'common/spinner' %>

  <% if @stock %>
    <div id="stock-lookup-results" class="well results-block">
      <strong>Symbol: </strong><%= @stock.ticker %>
      <strong>Name: </strong><%= @stock.name %>
      <strong>Price: </strong><%= @stock.price %>

      <% if current_user.can_add_stock? @stock.ticker %>
        <%= link_to 'Add to my stocks',
                    user_stocks_path(user: current_user, stock_ticker: @stock.ticker,
                                     stock_id: @stock.id ? @stock.id : ''),
                    method: :post, class: 'btn btn-xs btn-success' %>
      <% else %>
        <h4><span class="label label-warning">
          The stock cannot be tracked because you have already added

          <% if current_user.stock_already_added? @stock.ticker %>
            this stock.
          <% elsif !current_user.under_stock_limit? %>
            10 stocks.
          <% end %>
        </span></h4>
      <% end %>
    </div>
  <% end %>

  <div id="stock-lookup-errors"></div>
</div>

app/views/user_stocks/_form.html.erb
<%= form_for(@user_stock) do |f| %>
  <% if @user_stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_stock.errors.count, "error") %> prohibited this user_stock from being saved:</h2>

      <ul>
      <% @user_stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :stock_id %><br>
    <%= f.text_field :stock_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_stocks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Listing User Stocks</h1>
</div>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_stocks.each do |user_stock| %>
      <tr>
        <td><%= user_stock.user %></td>
        <td><%= user_stock.stock %></td>
        <td><%= link_to 'Show', user_stock %></td>
        <td><%= link_to 'Edit', edit_user_stock_path(user_stock) %></td>
        <td><%= link_to 'Destroy', user_stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User stock', new_user_stock_path %>

app/views/user_stocks/new.html.erb
<div class="page-header">
  <h1>New User Stock</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', user_stocks_path %>

app/views/users/my_friends.html.erb
<div class="page-header">
  <h1>My friends</h1>
</div>

<% if @friends.any? %>
  <div class="row">
    <div class="col-sm-10">
      <table class="table table-striped table-bordered table-condensed">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @friends.each do |friend| %>
            <tr>
              <td><%= friend.full_name %></td>
              <td><%= friend.email %></td>
              <td>
                <%= link_to 'View profile', friend, class: 'btn btn-primary btn-xs' %>
                <%= link_to 'Remove friend', friendship_path(friend), method: :delete,
                           data:{ confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <div class="row">
    <p class="lead">You don't have any friends yet, why not add some?</p>
  </div>
<% end %>

<%= render 'friends/lookup' %>

app/views/users/my_portfolio.html.erb
<div class="page-header">
  <h1>My portfolio</h1>
</div>

<%= render 'stocks/list' %>

<%= render 'stocks/lookup' %>

app/views/users/show.html.erb
<div class="page-header">
  <h1>User details</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Full name</strong></dt>
  <dd><%= @user.full_name %></dd>

  <dt><strong>Email</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<% if @user_stocks.any? %>
  <%= render 'stocks/list' %>
<% else %>
  <p class="lead">This user is not tracking any stocks</p>
<% end %>

<%= link_to 'Back', my_friends_path, class: 'btn btn-primary' %>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Finanace Tracker</h1>

  <p class="lead">Free to sign up and set up a portfolio of stocks.</p>
</div>